#!/bin/bash
set -x
# CUDA_VISIBLE_DEVICES=0,1
max_prompt_length=2048
max_response_length=12800
project_name='GRPO_val_16'
experiment_name='qwen_14b_limo_grpo_12800_128_accum_1_0_dynamic_dyn_avg_th_0.2_dyn_a_th-a_bar_n_10_2500_10000_zero_Li-avg_Li-avg_similar'

python3 -m verl.trainer.main_ppo \
    algorithm.adv_estimator=grpo \
    data.train_files=$HOME/dataset/train/train.parquet \
    data.val_files=$HOME/dataset/test/gather_data.parquet \
    data.train_batch_size=64 \
    data.val_batch_size=32 \
    data.max_prompt_length=${max_prompt_length} \
    data.max_response_length=${max_response_length} \
    data.filter_overlong_prompts=True \
    data.dataloader_num_workers=0 \
    data.truncation='error' \
    actor_rollout_ref.model.path=$HOME/models/Qwen3-14B-ft-limo \
    actor_rollout_ref.actor.optim.lr=1e-6 \
    actor_rollout_ref.model.use_remove_padding=True \
    actor_rollout_ref.actor.ppo_mini_batch_size=8 \
    actor_rollout_ref.actor.ppo_micro_batch_size_per_gpu=5 \
    actor_rollout_ref.actor.use_kl_loss=True \
    actor_rollout_ref.actor.kl_loss_coef=0.001 \
    actor_rollout_ref.actor.kl_loss_type=low_var_kl \
    actor_rollout_ref.actor.entropy_coeff=0 \
    actor_rollout_ref.actor.ulysses_sequence_parallel_size=2 \
    actor_rollout_ref.actor.checkpoint.save_contents=["model","optimizer","extra"] \
    actor_rollout_ref.model.enable_gradient_checkpointing=True \
    actor_rollout_ref.actor.fsdp_config.param_offload=True \
    actor_rollout_ref.actor.fsdp_config.optimizer_offload=True \
    actor_rollout_ref.rollout.log_prob_micro_batch_size_per_gpu=8 \
    actor_rollout_ref.rollout.enable_chunked_prefill=True \
    actor_rollout_ref.rollout.max_num_batched_tokens=$((max_prompt_length + max_response_length)) \
    actor_rollout_ref.rollout.tensor_model_parallel_size=2 \
    actor_rollout_ref.rollout.name=vllm \
    actor_rollout_ref.rollout.gpu_memory_utilization=0.75 \
    actor_rollout_ref.rollout.n=10 \
    actor_rollout_ref.rollout.val_kwargs.n=16 \
    actor_rollout_ref.rollout.val_kwargs.do_sample=True \
    actor_rollout_ref.rollout.val_kwargs.temperature=0.6 \
    actor_rollout_ref.rollout.val_kwargs.top_p=0.95 \
    actor_rollout_ref.ref.log_prob_micro_batch_size_per_gpu=8 \
    actor_rollout_ref.ref.fsdp_config.param_offload=True \
    trainer.critic_warmup=0 \
    trainer.logger='["console","wandb"]' \
    trainer.project_name=${project_name} \
    trainer.experiment_name=${experiment_name} \
    trainer.n_gpus_per_node=8 \
    trainer.nnodes=1 \
    trainer.save_freq=5 \
    +trainer.remove_previous_ckpt_in_save=True \
    trainer.test_freq=5 \
    trainer.del_local_ckpt_after_load=True \
    trainer.val_before_train=False \
    trainer.total_epochs=3  \
    trainer.default_local_dir="$HOME/verl/checkpoints/${project_name}/${experiment_name}" \
    trainer.validation_data_dir="$HOME/verl/gen_results/${project_name}/${experiment_name}" \
    +trainer.filter_easy_acc=1 \
    +trainer.filter_hard_acc=0 \
    reward_model.reward_manager='dynamic' $@